version: '3.8'

services:
  api-gateway:
    build: api-gateway
    container_name: 'api-gateway'
    volumes:
      - .:/opt/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - api-gateway/.env
    expose:
      - 8000
    ports:
      - '8000:8000'
  auth-server-grpc:
    build: servers/auth
    image: auth-server-grpc
    env_file:
      - servers/auth/.env
    expose:
      - 50000
    ports:
      - '50000:50000'
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: [ 'postgres', '-c', 'log_statement=all', '-c', 'log_destination=stderr' ]
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data: