# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"2\n\x0fRequestDataUser\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"5\n\x12ResponseCreateUser\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\rResponseLogin\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t2T\n\x11RequestCreateUser\x12?\n\nCreateUser\x12\x15.auth.RequestDataUser\x1a\x18.auth.ResponseCreateUser\"\x00\x32M\n\x10RequestLoginUser\x12\x39\n\tLoginUser\x12\x15.auth.RequestDataUser\x1a\x13.auth.ResponseLogin\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTDATAUSER']._serialized_start=20
  _globals['_REQUESTDATAUSER']._serialized_end=70
  _globals['_RESPONSECREATEUSER']._serialized_start=72
  _globals['_RESPONSECREATEUSER']._serialized_end=125
  _globals['_RESPONSELOGIN']._serialized_start=127
  _globals['_RESPONSELOGIN']._serialized_end=164
  _globals['_REQUESTCREATEUSER']._serialized_start=166
  _globals['_REQUESTCREATEUSER']._serialized_end=250
  _globals['_REQUESTLOGINUSER']._serialized_start=252
  _globals['_REQUESTLOGINUSER']._serialized_end=329
# @@protoc_insertion_point(module_scope)
